### ISSUE TITLE
Sign up with GitHub doesn't work

### ISSUE THREAD

**Issue by jonesmo** [uci-ml-repo/ucimlrepo-feedback#1]
**Describe the bug**
Tried to sign up on the beta with GitHub and got an error

**To Reproduce**
1. Click on Log In
2. Click on Sign Up
3. Click on Sign Up With GitHub
4. Receive "This site can't be reached: localhost refused to connect" error

**Desktop (please complete the following information):**
 - OS: OSX 11.4 Big Sur
 - Browser: Chrome
 - Version 91.0.4472.77 (Official Build) (x86_64)

**Comment by kevorkkeheian** [comment]
I faced the same issue. The authentication is redirecting to localhost instead of the uci-beta's authentication domain/link

**Comment by ap0nia** [comment]
This should be resolved now!
