### ISSUE TITLE
Add Feature that defines the units used in the attribute or variable

### ISSUE THREAD

**Issue by jxocean2018** [uci-ml-repo/ucimlrepo-feedback#14]
I am looking at a dataset on wastewater treatment that was uploaded by Spanish researcher, I assume they are using metric units, but was wondering if there is a way to have a legend with units for the variable.  This is really important in water data as folks in the west use million acre-feet / year and million gallons a day.

**Comment by rlongjohn** [comment]
Thank you for pointing this out! In the new version of the repository website, dataset donors now have the option to fill out a Features table about the variables in their dataset, including the units of measurement for each variable (e.g., see the [Iris dataset](https://doi.org/10.24432/C56C76)).
