### ISSUE TITLE
Some attributes of the validation file in UJIIndoorLoc Dataset is NULL

### ISSUE THREAD

**Issue by TracyWang-0** [uci-ml-repo/ucimlrepo-feedback#20]
**Describe the bug**
Hello, thank you for your contributions on this dataset. 
However, I find that some attributes of the validation file in UJIIndoorLoc Dataset is NULL, such as SpaceId and RelativePosition. It bothers me when I want to validate the accuracy of my model.

**Expected behavior**
Could you please provide these data or tell me how can I access these data ?

**Screenshots**
![image](https://user-images.githubusercontent.com/68034401/157611791-cf366422-65c1-4c74-adcd-a20c1c9afb81.png)

**Comment by rlongjohn** [comment]
Thank you for your question! It looks like this was done purposely by the authors in the validation data to simulate a more realistic localization scenario. From the corresponding paper (available [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7275492)): 
"[T]he database is split into two subsets: the training subset and the validation subset. In the training subset, the reference points are well-specified, being these points captured by, at least, two users. However, in the validation subset, the measures were taken at arbitrary points as would happen in a real localization system and, for this reason, these reference points (identified by SpaceID and Relative position) are not stored in the validation records. This fact is denoted by assigning the default value 0 to both fields."
