### ISSUE TITLE
Youtube04-Eminem.csv, datapoint corrupted

### ISSUE THREAD

**Issue by ghaccount** [uci-ml-repo/ucimlrepo-feedback#21]
**Describe the bug**
Youtube04-Eminem.csv, Line 271 
COMMENT_ID LneaDw26bFvv8RbyHRBDnA-4Bb1lhF9UlpzJf_5FkWM
Content is corrupted and has multiple datapoints.

**To Reproduce**
Youtube04-Eminem.csv, Line 271 
COMMENT_ID LneaDw26bFvv8RbyHRBDnA-4Bb1lhF9UlpzJf_5FkWM
Check the content of that COMMENT_ID 

**Expected behavior**
content contains single data point

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ap0nia** [comment]
Please provide more details. i.e. the url to the dataset page, the dataset ID or slug, name, etc. Will close unless there's further activity.
