### ISSUE TITLE
About the double donated dataset

### ISSUE THREAD

**Issue by serdarenginoglu** [uci-ml-repo/ucimlrepo-feedback#22]
To whom it may concern

I tried to donate the "Monolithic Columns in Troad and Mysia Region" dataset but failed. I request that the information entries for these two data sets be deleted so that I can try again. If editing is allowed, deleting one will suffice.

Best regards

Serdar Enginoğlu

**Comment by ap0nia** [comment]
Duplicate of #4, which has been fulfilled.
