### ISSUE TITLE
data not found

### ISSUE THREAD

**Issue by hillelMerran** [uci-ml-repo/ucimlrepo-feedback#27]
**Describe the bug**

**To Reproduce**
1. Go to https://archive-beta.ics.uci.edu/dataset/45/heart+disease
2. Click on 'Downloads'
3. See error '404 Not found'

**Comment by ap0nia** [comment]
Dataset page: https://archive.ics.uci.edu/dataset/45/heart+disease
Link to zip file: https://archive.ics.uci.edu/static/public/45/heart+disease.zip
