### ISSUE TITLE
The dataset download is not functioning on the new site. 

### ISSUE THREAD

**Issue by Hugomer** [uci-ml-repo/ucimlrepo-feedback#30]
{"statusCode":404,"message":"Cannot GET /static/public/296/diabetes+130+us+hospitals+for+years+1999+2008.zip","error":"Not Found"}

**Comment by ap0nia** [comment]
Dataset page: https://archive.ics.uci.edu/dataset/296/diabetes+130+us+hospitals+for+years+1999+2008
Link to zip file: https://archive.ics.uci.edu/static/public/296/diabetes+130+us+hospitals+for+years+1999+2008.zip
