### ISSUE TITLE
Looking for authors included in the victorian era authorship data set

### ISSUE THREAD

**Issue by gmonte29** [uci-ml-repo/ucimlrepo-feedback#36]
**Is your feature request related to a problem? Please describe.**

Hope you are well! I am working with the dataset linked below. The dataset includes passages and labels representing the authors of the given passage. The labels are 1-50. I was wondering if you had the author names that the labels 1-50 are assigned to.  Feel free to let me know if more information is needed!

https://archive.ics.uci.edu/ml/datasets/Victorian+Era+Authorship+Attribution

**Describe the solution you'd like**

The author names associated with the labels in the dataset

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ap0nia** [comment]
@uci-ml-repo/curators

**Comment by rlongjohn** [comment]
Thank you for your question! Table 3.1 in [this thesis](https://www.proquest.com/dissertations-theses/benchmarking-authorship-attribution-techniques/docview/2101510652/se-2?accountid=14509) provides the 50 author names. If for some reason that link doesn't work, here is the citation info: Gungor, Abdulmecit, Benchmarking Authorship Attribution Techniques Using Over A Thousand Books by Fifty Victorian Era Novelists, Purdue Master of Thesis, 2018-04

**Comment by gmonte29** [comment]
Thank your Ms. Longjohn!
