### ISSUE TITLE
Dataset download capability

### ISSUE THREAD

**Issue by thomas4269** [uci-ml-repo/ucimlrepo-feedback#39]
**Describe the bug**
Unable to access datasets. From the Archive site of the repository, I receive a '500 Internal Error' message when attempting to access any dataset and a '404 Not Found' message from the Beta site of the repository when attempting to download any dataset. 

**To Reproduce**
1. Go to 'http://archive.ics.uci.edu/dataset/183/communities+and+crime' / 'https://archive-beta.ics.uci.edu/dataset/183/communities+and+crime'
2. Click on 'download' for the Beta site of the repository
3. See error

**Expected behavior**
'500 Internal Error'/'404 Not Found' 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ventura 13.4
 - Browser: Chrome and Safarri
 - Version: 114.0.5735.90

<img width="1728" alt="Screenshot 2023-06-08 at 9 45 05 AM" src="https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/135986547/1e3e0fb2-c681-456f-85e6-67b4c9bd8052">
<img width="626" alt="Screenshot 2023-06-08 at 9 45 00 AM" src="https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/135986547/4e5a548e-7e6b-46cf-92e1-1d3d38be03ba">

**Comment by ap0nia** [comment]
Please try the first link again.
Here's the download link to the zip directly: http://archive.ics.uci.edu/static/public/183/communities+and+crime.zip
