### ISSUE TITLE
I recommend removing two wrong-donated datasets.

### ISSUE THREAD

**Issue by serdarenginoglu** [uci-ml-repo/ucimlrepo-feedback#4]
Dear Editor

I twice tried to donate a dataset in 2020.  However, I think that I have failed. I recommend removing this twice wrong-donated dataset. I have donated the dataset again now.

Best regards
 
Title: Monolithic Columns in Troad and Mysia Region

![I recommend removing two wrong-donated datasets](https://user-images.githubusercontent.com/86885112/124389462-dabc4c80-dcef-11eb-8e6b-d81d935e0570.jpeg)

**Comment by ap0nia** [comment]
They have been re-designated as "REJECTED", with the data archived internally.
