### ISSUE TITLE
Heart Disease Dataset URL Issue

### ISSUE THREAD

**Issue by ericspod** [uci-ml-repo/ucimlrepo-feedback#41]
**Describe the bug**
DOI link `https://doi.org/10.24432/C52P4X` now forwards to `https://archive.ics.uci.edu/dataset/45` which is broken, this URL should forward to `https://archive.ics.uci.edu/dataset/45/heart+disease` rather than show a 403 screen.

Dataset contents are now in a zip file rather than available for direct download, this will break a lot of notebooks and examples that rely on direct download of individual files from URLs. 

**To Reproduce**
1. Go to `https://archive.ics.uci.edu/dataset/45/heart+disease`
2. Click DOI link
3. Forwarded to `https://archive.ics.uci.edu/dataset/45` which is a 403 page.

**Expected behavior**
URL should forward to the page for the dataset

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser FF
 - Version 113.0.2 (64-bit)

**Comment by ericspod** [comment]
Virtually all existing URLs to dataset pages and data files appear broken now. There really needs to be forwarding links to fix all of these since so many tutorials, pages, notebooks, and other resources rely on these URLs considering how popular the database it.

**Comment by ap0nia** [comment]
> Virtually all existing URLs to dataset pages and data files appear broken now. There really needs to be forwarding links to fix all of these since so many tutorials, pages, notebooks, and other resources rely on these URLs considering how popular the database it.

Thank you for this information as well. I've created a new issue to track this feature #42

**Comment by ericspod** [comment]
> Thank you for informing us. Dataset URLs of the form `https://archive.ics.uci.edu/dataset/<dataset ID>` are supposed to redirect to the full URL and this has been fixed.
> 
> Let me know if this isn't the case, i.e. with the original URL https://archive.ics.uci.edu/dataset/45

Thanks, the DOI link appears working now. Thanks also for looking at the legacy URL issue, I think it's important to keep the old links but the new site is a good improvement otherwise.

**Comment by ap0nia** [comment]
@ericspod I think I've implemented something rudimentary to get us going.

Here's an example of a link that would be used by the old website (I presume, at least) https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/heart-disease.names

What do you think?

**Comment by ap0nia** [comment]
Thank you for confirming! The legacy website also allowed you to browse the file directory structure publicly, i.e. by clicking on files and navigating to sub-directories. I'm not really sure how important that particular feature is, but I'm glad that the website will remain functional for programmatic accesses.

**Comment by ericspod** [comment]
I would guess there are examples out there that would rely on directly accessing these files. Hopefully these changes will address most people's needs and see about further feedback. Thanks again!
