### ISSUE TITLE
Pressing buttons on side bar does not close after navigation

### ISSUE THREAD

**Issue by parmikmehra** [uci-ml-repo/ucimlrepo-feedback#43]
**Describe the bug**
When I click on the side bar and then press on any of the options like “browse datasets”, then it doesn't close the bar on iphone at least. This is annoying because the bar takes up about half my screen and I have to click outside of it to work.

**To Reproduce**
1. Go to homepage
2. Click on the three lines button on top left of page
3. Click on any option

**Expected behavior**
Navigate to page and close bar when clicked

**Smartphone (please complete the following information):**
 - Device: iphone 14 pro
 - OS: IOS 16.1.2
 - Browser: safari

**Comment by ap0nia** [comment]
Sounds like a skill issue to me! Won't fix :sunglasses:

Jk, had to setup a context API to close the drawer when a child link was clicked.
