### ISSUE TITLE
Dataset "donated on" date changes by -1 day on page load

### ISSUE THREAD

**Issue by dwjiang** [uci-ml-repo/ucimlrepo-feedback#44]
**Describe the bug**
Dataset "donated on" date changes by -1 day on page load. May be due to timezone or svelte hydration? Not sure.

**To Reproduce**
1. Go to any dataset page (e.g. https://archive.ics.uci.edu/dataset/2/adult).
2. "Donated on" date changes by -1 days.
3. Refresh page to reproduce.

**Expected behavior**
Date doesn't change after page load.

**Screenshots**
[screen-capture.webm](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/17039633/eedd8eda-e907-442f-bdce-46d9ec435214)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 113.0.5672.127

**Additional context**
- Timezone: PDT
- Also, congrats on website release! Very cool! 🎉

**Comment by ap0nia** [comment]
Yes I've also observed this ~~bug~~feature. I'm glad you're enjoying it as well :sunglasses:

Looks like it might be an SSR time-zone diff.
