### ISSUE TITLE
Download of Wisconsin Breast Cancer data not working

### ISSUE THREAD

**Issue by pmcgarvey** [uci-ml-repo/ucimlrepo-feedback#45]
**Describe the bug**
Working on Mac

**To Reproduce**
1. Go to (https://archive.ics.uci.edu/datasets?search=Breast%20Cancer%20Wisconsin%20(Diagnostic))
2. Click on 'Download'
'A zip file downloads it is small and uncompresses into an empty folder called Graphics.'
4. See error 'A zip file downloads it is small and uncompresses into an empty folder called Graphics.'

Note same problem on 
https://archive.ics.uci.edu/dataset/16/breast+cancer+wisconsin+prognostic

The https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original
works correctly 

**Expected behavior**
I get data
**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacBook Pro 13.4 (22F66) Ventura
 - Browser [Safari]
 - Version [Version 16.5 (18615.2.9.11.4)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ap0nia** [comment]
The missing dataset files have been located and the download links should work now. Please let me know if this isn't the case for you.

Here's a direct link to the zip download: https://archive.ics.uci.edu/static/public/17/breast+cancer+wisconsin+diagnostic.zip
