### ISSUE TITLE
p53+mutants Dataset. When I download the zip file and try extract it, I get the error  End-of-central-directory signature not found.

### ISSUE THREAD

**Issue by zwickey** [uci-ml-repo/ucimlrepo-feedback#48]
**Describe the bug**
The zip file gives an error that the **End-of-central-directory signature not found**. which indicates the file is corrupt
*
1. go to https://archive.ics.uci.edu/dataset/188/p53+mutants
2. Click on Download, or use wget
3. try to unzip
4. See the error

**Expected behavior**
the file unzips without any error
**Screenshots**
![image](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/41262027/e568e4b7-19f1-49e5-af8e-f0ca3006811d)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 22

**Comment by ap0nia** [comment]
Thank you for letting us know, it looks like the zip file was corrupted. I re-zipped the file and it seems to be working now. Please try again and let me know if it still doesn't work for you.

Dataset page: https://archive.ics.uci.edu/static/public/188/p53+mutants.zip
Zip file: https://archive.ics.uci.edu/static/public/188/p53+mutants.zip
