### ISSUE TITLE
No File Error when downloading dataset

### ISSUE THREAD

**Issue by nicolepengg** [uci-ml-repo/ucimlrepo-feedback#49]
**Is your feature request related to a problem? Please describe.**
This happened when I'm trying to download any dataset related to ASD (Autism Spectrum Disorder) from UCI. I've tried Adult, Adolescent and Tollder datasets and all of them give the no file error when I clicked on download button. I've tried switching browsers, clearing cache, searching through doi, disabling windows setting but none work. 

**Describe the solution you'd like**
I would like to know if there is any possibility that these datasets can be available again on the site or the download path can be fixed? 

**Describe alternatives you've considered**
Is there any alternative way for me to obtain these datasets?

**Comment by ap0nia** [comment]
Thank you for bringing this to our attention, I relocated the zip files to the proper location and the files should be obtainable now. Please let me know if this isn't the case for any of the following links.

Dataset page: https://archive.ics.uci.edu/dataset/419/autistic+spectrum+disorder+screening+data+for+children
Zip file: https://archive.ics.uci.edu/static/public/419/autistic+spectrum+disorder+screening+data+for+children.zip

Dataset page: https://archive.ics.uci.edu/dataset/420/autistic+spectrum+disorder+screening+data+for+adolescent
Zip file: https://archive.ics.uci.edu/static/public/420/autistic+spectrum+disorder+screening+data+for+adolescent.zip

Dataset page: https://archive.ics.uci.edu/dataset/426/autism+screening+adult
Zip file: https://archive.ics.uci.edu/static/public/426/autism+screening+adult.zip
