### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by v-mepa** [uci-ml-repo/ucimlrepo-feedback#50]
**Describe the bug**
The links for Download the Sentiment Labelled Sentences datasets from the UCI Machine Learning Repository are broken.

**To Reproduce**
1. Go to 'https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/data'
2. Click on  UCI Machine Learning repository > 'https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences'
![image](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/42360097/8fc734fe-89b4-4a80-b52c-dfc60eaac915)

4. Step 2 link opens a new tab 
5. Click on 'Download'

**Expected behavior**
The dataset should get downloaded. 

**Screenshots**
![image](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/42360097/ee753e7f-a37e-4468-947b-5393e8754ac5)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome 
 - Version 113.0.0.0

**Comment by ap0nia** [comment]
Thank you for informing us. I think it should be fixed now. Please try again and let me know if it isn't.
Here's the direct download link for the zip file: https://archive.ics.uci.edu/static/public/331/sentiment+labelled+sentences.zip

**Comment by v-mepa** [comment]
Yes its working now. Thank you for looking into this.
