### ISSUE TITLE
Not a feature request or issue but I need some information.

### ISSUE THREAD

**Issue by Arindam240143** [uci-ml-repo/ucimlrepo-feedback#51]
I am doing a project on the Seoul Bike Sharing Demand data set and would like to know what Visibility - 10m denote? Also the measurement unit for Visibility would be nice. I would appreciate if you can share me the information asap.

**Comment by rlongjohn** [comment]
Thank you for your question! I believe that "Visibility - 10m" indicates that the measurement unit for Visibility is tens of meters. For example, a value of 793 for Visibility indicates that the visibility was 793 x 10 meters.
