### ISSUE TITLE
no data here: https://archive.ics.uci.edu/dataset/146/statlog+landsat+satellite

### ISSUE THREAD

**Issue by 4AlexMin** [uci-ml-repo/ucimlrepo-feedback#52]
**Describe the bug**
The downloaded file only contains 2 images. The description specified Multivariate dataset and provided information for attributes.

**Comment by ap0nia** [comment]
Thank you for informing us. This should be corrected now. Could you try downloading the file again and let us know if there's anything missing? Thanks!

Here's the direct download link to the zip file:  https://archive.ics.uci.edu/static/public/146/statlog+landsat+satellite.zip
