### ISSUE TITLE
The downloaded zip file contains *.exe file which could be malicious. 

### ISSUE THREAD

**Issue by ringerlin** [uci-ml-repo/ucimlrepo-feedback#54]
**Describe the bug**
The downloaded zip from the link below contains *.exe file, which I think may be malicious.
https://archive.ics.uci.edu/dataset/799/single+elder+home+monitoring+gas+and+position

**To Reproduce**
1. Go to https://archive.ics.uci.edu/dataset/799/single+elder+home+monitoring+gas+and+position
2. Click on Download
3. Go to the download folder and open downloaded zip file without extracting it
4. You can see the *.exe file

**Expected behavior**
The zip file should not contain *.exe

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version:  114.0.1823.67 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ap0nia** [comment]
Thank you for reporting this issue. I've loaded the correct file contents onto the server now.
