### ISSUE TITLE
Empty Census-Income (KDD) data files

### ISSUE THREAD

**Issue by Gio-Formichella** [uci-ml-repo/ucimlrepo-feedback#55]
I'm unable to download the Census-Income (KDD) dataset

When I press the download button I obtain the .zip folder but the data files in it are empty. The files are .gz and .tar.gz, when I try to unzip them with 7-zip I get the error that the file is not an archive and when I open them they just contain a path, i.e. ../../../../../kdd0/databases/census-income/census.tar.gz

I'm using windows 11 and chrome as my browser

**Comment by ptruong0** [comment]
Should work now, the census.tar.gz file contains three files for training data, test data, and information. I removed the other .gz files.
