### ISSUE TITLE
US Census data (1990) download has no data

### ISSUE THREAD

**Issue by yushangdi** [uci-ml-repo/ucimlrepo-feedback#56]
**Describe the bug**
 I'm trying to download this dataset: http://archive.ics.uci.edu/dataset/116/us+census+data+1990

The downloaded zip only contains some alias that could not be opened. There's no dataset.

I'm using chrome. 

**To Reproduce**
Click download on http://archive.ics.uci.edu/dataset/116/us+census+data+1990. 

**Screenshots**
![Screen Shot 2023-08-12 at 8 24 36 PM](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/22356083/9c51a3a8-f626-467a-b3a2-777064130f7b)

**Comment by ptruong0** [comment]
Fixed, thanks for letting us know
