### ISSUE TITLE
No Dataset file

### ISSUE THREAD

**Issue by AhmedGHDev** [uci-ml-repo/ucimlrepo-feedback#57]
Good evening,
I was trying to download the dataset of `One-hundred plant species leaves data set` [https://archive.ics.uci.edu/dataset/241/one+hundred+plant+species+leaves+data+set]

from link:
https://archive.ics.uci.edu/static/public/241/one+hundred+plant+species+leaves+data+set.zip

but the file does not exist on your sever.

**Comment by AhmedGHDev** [comment]
another one
https://archive.ics.uci.edu/static/public/271/activities+of+daily+living+adls+recognition+using+binary+sensors.zip

**Comment by ptruong0** [comment]
Both files have been recovered. Thanks for reporting this

**Comment by ptruong0** [comment]
The first two datasets have been recovered, but unfortunately we are missing the third on our end. Recorded in issue #40

**Comment by AhmedGHDev** [comment]
https://archive.ics.uci.edu/static/public/559/bar+crawl+detecting+heavy+drinking.zip

**Comment by ptruong0** [comment]
Thanks for finding all these. I've recorded these datasets in #40, and have recovered some of them.
