### ISSUE TITLE
Flags Dataset

### ISSUE THREAD

**Issue by bdhayes01** [uci-ml-repo/ucimlrepo-feedback#60]
In the Flags dataset at URL: https://archive.ics.uci.edu/dataset/40/flags, nations in asia and africa are both listed as 4 in the ".names", 7, landmass section, .zip file. This is not actually true, but it is in the names file. 

Below is the exact line:
7. Attribute Information:
   1. name	Name of the country concerned
   2. landmass	1=N.America, 2=S.America, 3=Europe, **4=Africa, 4=Asia**, 6=Oceania

Thanks!

**Comment by ptruong0** [comment]
Thanks
