### ISSUE TITLE
Comments and/or rating system on the web site

### ISSUE THREAD

**Issue by DrMichaelGloeckler** [uci-ml-repo/ucimlrepo-feedback#62]
I have already downloaded several data sets to use in my course on predictive maintenance and I really appreciate it. Unfortunately, there are data sets that are hardly documented or probably contain incorrect data. 

The data sets have very different quality when it comes to the documentation and the data themselves. The ability to comment on data sets or a rating system on the website would be helpful to distinguish the valuable from the less valuable data sets. 

Best regards
Michael Gloeckler

**Comment by ptruong0** [comment]
Thanks for the idea! We will start to work on this feature.

**Comment by ptruong0** [comment]
This feature is live, please check it out
