### ISSUE TITLE
Empty file in Musk dataset

### ISSUE THREAD

**Issue by DryDew** [uci-ml-repo/ucimlrepo-feedback#64]
Hi,
I'm trying to access the musk dataset: https://archive.ics.uci.edu/dataset/75/musk+version+2. However, the downloaded file is empty. Could you please check it out and fix it? Thanks.

Best

**Comment by ptruong0** [comment]
Turns out the files for both versions were stored inside the Musk (version 1) dataset. The files for version 2 should all be there now.
