### ISSUE TITLE
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

### ISSUE THREAD

**Issue by BossYeah** [uci-ml-repo/ucimlrepo-feedback#65]
Run the following code in Jupiter Notebook:

from ucimlrepo import fetch_ucirepo, list_available_datasets
list_available_datasets()

Showing the following errors:

SSLCertVerificationError                  Traceback (most recent call last)
[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in do_open(self, http_class, req, **http_conn_args)
   1347             try:
-> 1348                 h.request(req.get_method(), req.selector, req.data, headers,
   1349                           encode_chunked=req.has_header('Transfer-encoding'))

17 frames
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)>

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ucimlrepo/fetch.py](https://localhost:8080/#) in fetch_ucirepo(name, id)
     67         data = json.load(response)
     68     except (urllib.error.URLError, urllib.error.HTTPError):
---> 69         raise ConnectionError('Error connecting to server')
     70 
     71     # verify that dataset exists

ConnectionError: Error connecting to server

**Comment by tikkss** [comment]
The server certificate has expired 2023-11-12T08:59:59+09:00 in https://archive.ics.uci.edu

**Comment by ptruong0** [comment]
Apologies for the downtime, there was a delay in renewing our SSL certificate

**Comment by tikkss** [comment]
Thanks!
