### ISSUE TITLE
ConnectionError: Error connecting to server

### ISSUE THREAD

**Issue by nafamubarokhusni** [uci-ml-repo/ucimlrepo-feedback#66]
I can't import dataset to my jupyter notebook
![Screenshot from 2023-11-12 20-27-58](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/79038126/2eb091cc-4521-4b09-a53b-770594a93fde)
![Screenshot from 2023-11-12 20-27-44](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/79038126/d3098ab0-9189-4253-889d-f73be5814a17)

**Comment by joconnell521** [comment]
I am also having this issue seems that some certificate has expired

**Comment by ptruong0** [comment]
Apologies for the downtime, there was a delay in renewing our SSL certificate
