### ISSUE TITLE
Import in python not working

### ISSUE THREAD

**Issue by eekenpiet** [uci-ml-repo/ucimlrepo-feedback#69]
Using the command:

connectionist_bench_sonar_mines_vs_rocks = fetch_ucirepo(id=151)

I get the error:

(<class 'ucimlrepo.fetch.DatasetNotFoundError'>, DatasetNotFoundError("Cannot read properties of null (reading 'toDateString')"), <traceback object at 0x7f8fe2eba6c0>)

Also if I use "name=....."
What to do?

**Comment by ptruong0** [comment]
Thanks for reporting this issue, it should work now
