### ISSUE TITLE
Can't download certain datasets

### ISSUE THREAD

**Issue by Devu-shah** [uci-ml-repo/ucimlrepo-feedback#7]
**Describe the bug**
I tried to get a dataset from the new website of UCI ML repo.
This is what I am trying to download: https://archive-beta.ics.uci.edu/ml/datasets/Traffic%20Flow%20Forecasting
But I am redirected to a page showing 404 Not found error

**To Reproduce**
1. Go to 'https://archive-beta.ics.uci.edu/ml/datasets/Traffic%20Flow%20Forecasting'
2. Scroll down to 'end of page'
3. click on: Traffic Flow Forecasting
4. Click download

**Expected behavior**
To download the dataset

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser: EDGE
 - Version: 93.0.961.47

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ap0nia** [comment]
Try the more recently uploaded dataset: https://archive.ics.uci.edu/dataset/734/traffic+flow+forecasting-1
Download zip: https://archive.ics.uci.edu/static/public/734/traffic+flow+forecasting-1.zip
