### ISSUE TITLE
ConnectionError: Error connecting to server

### ISSUE THREAD

**Issue by ginganinja04** [uci-ml-repo/ucimlrepo-feedback#72]
Cannot connect to server using Jupyter Notebook
![Screen Shot 2024-03-11 at 12 18 04 PM](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/118851202/1db2da6e-d2a0-4713-82d7-9801b1cf9654)

**Comment by ptruong0** [comment]
Hi, could you give more details for reproducing this error?

**Comment by YTushar18** [comment]
Hello Team
Is this resolved? as I'm facing this same issue...

This is coming up when we I use _fetch_ucirepo()_ 
![image](https://github.com/uci-ml-repo/ucimlrepo-feedback/assets/32396594/8067c715-4704-4de1-a121-8bf05eb3e452)

**Comment by ptruong0** [comment]
I tried fixing it with this: [https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/42334357#42334357](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/42334357#42334357.)

 I haven't been able to reproduce this error, so please let me know if it works with the newest version (0.0.6).

**Comment by ginganinja04** [comment]
All I did was use the given code for using the heart health data as instructed in https://archive.ics.uci.edu/dataset/45/heart+disease using the code :

## install the ucimlrepo package 
pip install ucimlrepo



from ucimlrepo import fetch_ucirepo 
  

heart_disease = fetch_ucirepo(id=45) 
  

X = heart_disease.data.features 
y = heart_disease.data.targets 
  
print(heart_disease.metadata) 
  
print(heart_disease.variables)

**Comment by andrew-wang0** [comment]
Hi, this issue is being closed due to inability to reproduce
