### ISSUE TITLE
Covertype dataset

### ISSUE THREAD

**Issue by emiliocantuc** [uci-ml-repo/ucimlrepo-feedback#73]
**Describe the bug**
Fetching the dataset with Python's ucimlrepo.fetch_ucirepo results in a  'Wilderness_Area' feature that differs from the one in the hosted ZIP. The feature should contain 4 possible values for the wilderness area. In the original dataset these were one hot encoded. The fetched dataset has only a binary  'Wilderness_Area' column. 

**To Reproduce**
Download the Covertype dataset from the hosted ZIP and fetch with ucimlrepo.fetch_ucirepo and inspect the 'Wilderness_Area' features in both.

**Comment by ptruong0** [comment]
Thanks for notifying us of this issue. The 4 Wilderness_Area columns have been recovered in the Python version.
