### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by jwc-dwa** [uci-ml-repo/ucimlrepo-feedback#74]
**Describe the bug**
Cannot Login or access data sets.  Redirected to a page with a 500 Internal Error Message

**To Reproduce**
1. Go to '[...](https://archive.ics.uci.edu/datasets)'
2. Click on 'Iris'
3. Try to download data

**Expected behavior**
Access the website and utilize the data.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MS
 - Browser [chrome]
 - Version [Version 124.0.6367.156 (Official Build) (64-bit)]

**Additional context**
It seems as though there is no access to your repository

**Comment by andrew-wang0** [comment]
This issue is being closed due to inability to reproduce. Please provide further information if this is a ongoing issue.
