### ISSUE TITLE
Regarding request to delete the uploaded data 

### ISSUE THREAD

**Issue by Faisal1234-hue** [uci-ml-repo/ucimlrepo-feedback#78]
**Additional context**
Hello there . I want to delete my "Employee turnover intention data(TOI)" . Please help me do so.  I want to upload the data later since more please have started answering. 

[Employee turnover intention data (TOI).xlsx](https://github.com/user-attachments/files/15524651/Employee.turnover.intention.data.TOI.xlsx)

**Comment by ptruong0** [comment]
Hello, we have deleted your dataset. If you would like to donate with the new data file, please complete the donation form again.

**Comment by Faisal1234-hue** [comment]
thanks.
