### ISSUE TITLE
Error with cuff less blood pressure

### ISSUE THREAD

**Issue by rkrishnan53** [uci-ml-repo/ucimlrepo-feedback#83]
**Describe the bug**
Get error message when trying to access cuff less blood pressure repository

**To Reproduce**
1. Go to 'search'
2. Click on 'cuff less blood pressure'

**Expected behavior**
MIMIC blood pressure dataset

**Screenshots**
[Error message.pdf](https://github.com/user-attachments/files/16970462/Error.message.pdf)
[Search result.pdf](https://github.com/user-attachments/files/16970463/Search.result.pdf)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Sonoma 14.6.1
 - Browser [e.g. chrome, safari] Chrome AND Safari
 - Version [e.g. 22] Safari Version 17.6 (19618.3.11.11.5)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrew-wang0** [comment]
Hi @rkrishnan53, this issue was not able to be reproduced. If you continue to have this error, please let us know
