### ISSUE TITLE
Upload time for a donated dataset 

### ISSUE THREAD

**Issue by Faisal1234-hue** [uci-ml-repo/ucimlrepo-feedback#84]
Dear sir,

good day. I am trying to donate a dataset on uci machine learning . Can you please let me know how much time it would take for getting the result of the dataset ?

Kindest regards

Faisal

**Comment by andrew-wang0** [comment]
Hi @Faisal1234-hue, dataset donations are reviewed by our librarians @rlongjohn and @markellekelly. If you have specific inquires, you can also email ucirepository@gmail.com

**Comment by Faisal1234-hue** [comment]
Hello.

DO I need  to do anything additional ?

**Comment by andrew-wang0** [comment]
No you shouldn't have to do anything additional. However, if you have any questions on the progress of your review, you can use the contact information given above.
