### ISSUE TITLE
SSL out of date

### ISSUE THREAD

**Issue by Mike-7777777** [uci-ml-repo/ucimlrepo-feedback#90]
## Expected Behavior

Normally enter the webpage without warning why chrome.

## Current Behavior

Warning from Chrome that the SSL certificate was expired yesterday.

## Possible Solution

Update the SSL certificate.

## Steps to Reproduce

1. Go to https://archive.ics.uci.edu/
2. 
3.

**Comment by andrew-wang0** [comment]
Hi @Mike-7777777. Thanks for informing us of this issue. We have renewed our certificate, and it should be resolved.

Let us know if you have any more issues.
